### ISSUE TITLE
[Critical] ДОБАВИТЬ ЗАВИСМОСТЬ В ПОМНИК ПРОЕКТА

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1105]
Сейчас при скачивании всего проекта из JDN - мы используем шаблонhttps://github.com/jdi-templates/jdi-light-testng-empty-template

Но с ним - есть одна проблема - pom.xml содержит только ссылку на пакет элементов HTML5.
![image](https://user-images.githubusercontent.com/26869421/225320935-944f4bd6-f226-48ab-961c-55e618f9c879.png)

А у нас - может быть и MaterialUI и/или Vuetify и так далее.
Поэтому.
При скачивании шаблона - нужно не только добавлять правильные импорты в каждый ПО как мы делаем сейчас, но и добавлять депенденси в помник (на тот же уровень где у нас депенденси на HTML5

Для Material UI (т.е. если в проекте есть хотя бы один Material UI Page Object) нужно добавлять:
```
<dependency>
<groupId>com.epam.jdi</groupId>
<artifactId>jdi-light-materialui</artifactId>
<version>${jdi.version}</version>
</dependency>

```
Для Vuetify (т.е. если в проекте есть хотя бы один Vuetify Page Object) нужно добавлять:
```
<dependency>
<groupId>com.epam.jdi</groupId>
<artifactId>jdi-light-vuetify</artifactId>
<version>${jdi.version}</version>
</dependency>

```

**Comment by MariiaNebesnova** [comment]
https://github.com/jdi-templates/jdi-light-testng-empty-template/blob/main/pom.xml

**Comment by MariiaNebesnova** [comment]
for pre-release implementation MUI dependency block will be always uncommented, because of the original template.
before release we will ask Natalia to edit it in the original repo and check the template generation right before publishing release.

**Comment by MariiaNebesnova** [comment]
[3.9.422](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.422)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.422 Back-end v 0.2.27

Test result - **fail**
Vuetify dependency is commented out if a Vuetify PO is presented in a project.

**Steps to reproduce:**

1. Open any page containing Vuetify elements (e.g. https://vuetifyjs.com/en/components/forms/)
2. Generate page object via JDN plugin using Vuetify library and xPath locator type
3. Save locators
4. Click _Download all_ button
5. Unzip and open downloaded project
6. Open pom.xml file
7. Scroll down to the dependencies section

**Expected result:** Vuetify dependency is uncommented

**Actual result:** Vuetify dependency is commented out
![2023-03-22 13_04_48-](https://user-images.githubusercontent.com/106632366/226900098-fcf0b70a-d8ea-40a1-a2a4-3c7b5c3ecc8c.jpg)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.425 Back-end v 0.2.27

The bug is fixed.
Dependencies in pom.xml currently look as in following screenshots:

1. If Material UI PO only has been created
![2023-03-23 11_37_33-mui](https://user-images.githubusercontent.com/106632366/227179607-26f19de7-bad5-44e5-94f2-6e4c60ddd58e.jpg)

2. If HTML5 PO only has been created
![2023-03-23 11_41_25-html5](https://user-images.githubusercontent.com/106632366/227179723-181b4294-74da-4257-896e-2b31a4d01940.jpg)

3. If Vuetify PO only has been created
![2023-03-23 11_39_09-vuetify](https://user-images.githubusercontent.com/106632366/227179690-512ee4c8-5bc7-4aa3-813a-60de53766b75.jpg)

4. If all three POs have been created
![2023-03-23 11_24_40-all-three-po)](https://user-images.githubusercontent.com/106632366/227179577-0080a953-ce51-4a6c-8cff-69ba6fb993a5.jpg)

Commented and uncommented blocks are currently correct according to the [developers comment](https://github.com/jdi-testing/jdn-ai/issues/1105#issuecomment-1477524541).
