### ISSUE TITLE
Перенос энвароментов на внешний хостинг

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1664]
Необходимо перенести наши облачные бэкэнды на внешнюю площадку (внутренняя - закрывается 1 апреля и это - не шутка).
Для этого нужно:
 - [x] Составить список возможных решений для выбора
 - [x] Перенести существующие энвароменты на новую площадку - Hetzner - 8 vCPU / 16 GB
 - [x] Создать версию фронта которая смотрит на новый бэк - @Iogsotot 
 - [x] Обновить документацию
 - [x] Обновить скрипты

**Comment by ivnglkv** [comment]
https://docs.google.com/spreadsheets/d/1eTPkaGaZ1PRlRgUWq0VcPbLaH2pM1JYTfWK73-t_kow/edit

**Comment by Iogsotot** [comment]
**Prod build:**

![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/e9e2b2af-7af2-4453-ba52-15265e7353ab)
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/bfd6e90e-cecf-4cbb-8db9-3794e0e11ed7)
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/e15ad844-905e-492e-9910-19122eb43909)
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/7df4a967-1650-4f95-9591-e1c426ccb710)

html5-predict failed:
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/d069336e-af2e-45d3-9dd3-c54e7b4f1b90)
mui-predict failed:
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/d2d99e1e-f373-4cff-89b1-0aefaea2cb38)
WS I can't check because of the errors above

**Dev build:**
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/def11ba5-b3cd-4199-a1d7-105085e74538)
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/f1cc12bb-3d01-4009-ad82-80ec1c495f5c)
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/7940ede5-455e-4b1a-b99c-5977ae6cb599)
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/8a199645-5857-4bd2-86c9-de413d0c1d6f)

html5-predict failed:
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/997429de-5212-4f8e-ba80-f5475c06671e)
mui-predict failed:
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/2165ff7d-1fba-402a-acca-dc63a509d12d)
WS I can't check because of the errors above

@ivnglkv  pls check, what's wrong with the failed endpoints?

**Comment by ivnglkv** [comment]
I've checked, there was a missing Docker image `selenoid/vnc_chrome:118.0`. I've pulled it with `docker image pull selenoid/vnc_chrome:118.0`. Everything should be working now

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1680
[3.15.11](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.11)

**Comment by InnaRadionova** [comment]
Verified JDN v 3.15.11 Back-end v 0.2.62
[jdi-light-testng-empty-template-main.zip](https://github.com/jdi-testing/jdn-ai/files/14634318/jdi-light-testng-empty-template-main.zip)
