### ISSUE TITLE
[Low]The plugin returns to the start view when scrolling the web page

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#250]
JDN v 3.1.157
Back-end v 2022-03-30-06.47.33
Chrome

https://material.io/components/buttons

1) click New page object
2) generate 
3) wait for the locators to load
4) start scrolling down the page
5) the Locator List disappears from the plugin. the plugin refreshes to the home page.

(while scrolling, the page url changes from https://material.io/components/buttons to https://material.io/components/buttons#usage )

**Comment by MariiaNebesnova** [comment]
добавление хеша плагин принимает за рефреш страницы и поэтому, все очищается. выяснить. почему не вызывается confirm ?

**Comment by MariiaNebesnova** [comment]
1 pt - fe

**Comment by AlexeyGirin** [comment]
Берём на инвестигацию - можно ли это пофиксить в принципе?

**Comment by MariiaNebesnova** [comment]
can't be reproduced because site's behavior is changed.
for now haven't found a web page that would add hashes while scrolling.
but if just to add hash to url in address bar - site scroll and plugin doesn't recognize it as a page reload. opened https://developer.mozilla.org/en-US/docs/Web/XPath/Introduction_to_using_XPath_in_JavaScript and added hash https://developer.mozilla.org/en-US/docs/Web/XPath/Introduction_to_using_XPath_in_JavaScript#notes

**Comment by andrei-mikhailovskii** [comment]
The bug is not reproducible.
Haven't found a web page that adds hashes while scrolling.
If a hash is added to the URL, web page scrolls and the plugin doesn't recognize it as a page reload (see attached screencast).

https://user-images.githubusercontent.com/106632366/230915034-b65a220f-c391-4c2b-b3af-652020b9d801.mp4


Based on that, the bus is closed.

JDN v 3.10.440 Back-end v 0.2.31
Windows 10 / Chrome Version 112.0.5615.50 (Official Build) (64-bit)
