### ISSUE TITLE
[US-14-2-5] "Back" action for PageObject list & "Edit list" option

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#260]
after #256 
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/22315067/US-14-2+Identify+elements+in+Page+Objects#UC-14-2-5-Clicking-on-%E2%80%9CBack%E2%80%9D-button

**Comment by MariiaNebesnova** [comment]
2 pt - fe

**Comment by MariiaNebesnova** [comment]
3.1.120

**Comment by IoffeM** [comment]
reopened

JDN v 3.1.120
Back-end v 2022-02-12-11.36.19
Chrome

Back button in generation phase - passed
Go back modal - passed

Extra Back button after confirmation!
We have 3 pages: 
  1) start page (no Back button) - ok
  2) generation page (there is a back button) - ok
  3) page objects list after confirmation page (is a copy of start page but there is a back button) - should be fixed because when we go back and back from the 3 page to 1, we can see that 1 page has been updated as 3 page. There is no need in Back button after confirmation to go back to generation page (page object editing anyway will be available through other buttons)
The current behavior gif is attached
![back1](https://user-images.githubusercontent.com/98175427/154257459-cc76f5a7-da9c-4d3d-be9c-248da9c740a4.gif)


test cases and mind map are updated

**Comment by IoffeM** [comment]
qa - 0.5pt

**Comment by AlexeyGirin** [comment]
Основная проблема которую обнаружила Маргарита, что кнопка Бэк не соотносится с ПО в который она нас возвращает. Необходимо придумать как сделать это более очевидным (сейчас - Бэк как бы относится ко всем списку ПО)

**Comment by ioffem** [comment]
one more detail: no matter what we decide with it, it should fit the screen. currently it looks as on screenshot below
<img width="532" alt="Screen Shot 2022-03-05 at 10 20 54 AM" src="https://user-images.githubusercontent.com/98175427/156873140-e8957898-2ae6-4eaf-ba25-3fd98432795e.png">

**Comment by SemyonKuznetsov** [comment]
[Figma link](https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=4729%3A270165
<img width="472" alt="Снимок экрана 2022-03-17 в 10 37 41" src="https://user-images.githubusercontent.com/101407186/158759829-b3a85f22-569d-49a1-9413-348af0e8ec81.png">
)

**Comment by AlexeyGirin** [comment]
Решили - накрывать страничку справа серой вуалью делающей её недоступной для кликов

**Comment by SemyonKuznetsov** [comment]
<img width="650" alt="Снимок экрана 2022-03-21 в 10 43 46" src="https://user-images.githubusercontent.com/101407186/159221144-1838a1a5-5267-4256-b8e2-4059e063b40d.png">

**Comment by MariiaNebesnova** [comment]
3.1.148

**Comment by ioffem** [comment]
REOPENED

JDN v 3.1.148
Back-end v 2022-02-12-11.36.19
Chrome

1. Extra Back button in the locators list (not at editing step). It should appear only if user clicks Edit list
2. At the editing step: back button clicking leads to modal with not clickable buttons appearance. No way to close it and try again
3. In order to fix page object and skip broken modal user can reload the page. After clicking Edit list again he gets empty plugin tab and console errors
<img width="1397" alt="Screen Shot 2022-03-23 at 9 48 39 AM" src="https://user-images.githubusercontent.com/98175427/159639829-149a768a-9e58-41f6-8cb3-1e3eb256c151.png">

**Comment by MariiaNebesnova** [comment]
3.1.149

**Comment by ioffem** [comment]
JDN v 3.1.150
Back-end v 2022-02-12-11.36.19
Chrome

done
test cases and mind map are updated
