### ISSUE TITLE
Обновить ReadMe

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#894]
Main:
- [ ] небольшой summary, что это за плагин, для чего это и для кого
- [ ] описать работу в инкогнито режиме - сорямба - сейчас этот режим не поддерживается
- [ ] описть advanced calculation
- [ ] описать работу фильтров, что с помощью них можно создавать нужный тип PO
- [ ] обновить скриншоты
- [ ] невозможность использования плагина более чем на 1 табе.
- [ ] #920 

Server part:
- [ ] Сам заголовок сервер парт озадачил, видимо будет серверная часть видимо нужно уточнить для чего почему, ну видимо они должны как-то коннектиться
- [ ] Почти все пользователи запутались в инструкциях докера и впн (запустил ВПН и начал разворачивать докер)
- [ ] непонятно что такое dockside view
- [ ] если без впн запустить плагин, то после неудачного Trying to access server..., предложить попробовать перезагрузить страницу или проверить VPN, так как иногда пользователи быстро открывают плагин, не дождавшись полного включения впн и плагин выдаёт инструкцию для поднятия сервера, надо просто подсказать перезагрузить плагин (закрыть/открыть или перезагрузить страницу может быть)
![image](https://user-images.githubusercontent.com/101407186/211314529-3ddcd8bf-e5a1-4dd1-a124-fcf1ccf9fb52.png)
- [ ] windows 10 изменить инструкцию по пользованию докером:
в винде есть WSL - windows subsystem for linux, и он предлагает ставить не Docker Desktop (который по его словам на епамовсих тачках надо просить аппрув на установку), а впаять линуксовый докер в WSL - РЕШИЛИ ЭТО НЕ ДЕЛАТЬ

Download:
- [ ] что и по какой кнопке скачивается, в чём разница, как открыть архив и java файлы, как использовать
- [ ] как открывать файл в идее

**Comment by SemyonKuznetsov** [comment]
почему плагина нет в инкогнито режиме? это так должно быть?

**Comment by AlexeyGirin** [comment]
> почему плагина нет в инкогнито режиме? это так должно быть?

Хотим поддержать работу в инкогнито режиме

**Comment by AlexeyGirin** [comment]
https://github.com/jdi-testing/jdn-ai/blob/issue_894/README.md

**Comment by andrei-mikhailovskii** [comment]
Test result - fail
Misprint in "Intellij IDEA" name (currently - "Intellej IDEA")
![image](https://user-images.githubusercontent.com/106632366/221144339-061a2f09-71f3-4da0-8d4f-5eb2c363eb5d.png)

**Comment by AlexeyGirin** [comment]
Сделать необходимые изменения что бы на фронте отображалось нормально - МАША

**Comment by MariiaNebesnova** [comment]
[3.8.401](https://github.com/jdi-testing/jdn-ai/releases/tag/3.8.401)

**Comment by andrei-mikhailovskii** [comment]
Test result - fail
Misprint in the word _three_ (actual result - _thee_).
Also, unnecessary comma before _if_ is placed.
![image](https://user-images.githubusercontent.com/106632366/221877743-925b1a36-b04f-4fa8-bb33-3cc474cc9c52.png)

Also, it would be more correct to write _to launch the backend server locally_ instead of _to launch locally the backend server_
![image](https://user-images.githubusercontent.com/106632366/221878455-2d2aa806-f83c-44cb-96cf-294bd0783109.png)

In the _Instructions to set up manually_ section, it has to be _subfolder's level_ instead of _subfolders level_ and DevTools instead of Devtools
![image](https://user-images.githubusercontent.com/106632366/221879987-48d58b8c-b6f9-46db-b138-1b28d078b7ba.png)

**Comment by MariiaNebesnova** [comment]
first two are fixed in [Release 3.9.403](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.403)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.405

Test result - **pass**
